package com.domker.app.doctor.detail.permission

import android.content.res.Resources
import com.domker.app.doctor.R


/**
 * 通过给定权限的名字，获取详细的描述
 */
fun getPermissionDetail(resources: Resources, permission: String): String {
    return when (permission) {
        "android.permission.ACCESS_ALL_DOWNLOADS" -> resources.getString(R.string.ACCESS_ALL_DOWNLOADS)
        "android.permission.ACCESS_CACHE_FILESYSTEM" -> resources.getString(R.string.ACCESS_CACHE_FILESYSTEM)
        "android.permission.ACCESS_CHECKIN_PROPERTIES" -> resources.getString(R.string.ACCESS_CHECKIN_PROPERTIES)
        "android.permission.ACCESS_COARSE_LOCATION" -> resources.getString(R.string.ACCESS_COARSE_LOCATION)
        "android.permission.ACCESS_COARSE_UPDATES" -> resources.getString(R.string.ACCESS_COARSE_UPDATES)
        "android.permission.ACCESS_DOWNLOAD_MANAGER" -> resources.getString(R.string.ACCESS_DOWNLOAD_MANAGER)
        "android.permission.ACCESS_DRM" -> resources.getString(R.string.ACCESS_DRM)
        "android.permission.ACCESS_FINE_LOCATION" -> resources.getString(R.string.ACCESS_FINE_LOCATION)
        "android.permission.ACCESS_GPS" -> resources.getString(R.string.ACCESS_GPS)
        "android.permission.ACCESS_LOCATION" -> resources.getString(R.string.ACCESS_LOCATION)
        "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" -> resources.getString(R.string.ACCESS_LOCATION_EXTRA_COMMANDS)
        "android.permission.ACCESS_MOCK_LOCATION" -> resources.getString(R.string.ACCESS_MOCK_LOCATION)
        "android.permission.ACCESS_NETWORK_STATE" -> resources.getString(R.string.ACCESS_NETWORK_STATE)
        "android.permission.ACCESS_SURFACE_FLINGER" -> resources.getString(R.string.ACCESS_SURFACE_FLINGER)
        "android.permission.ACCESS_SUPERUSER" -> resources.getString(R.string.ACCESS_SUPERUSER)
        "android.permission.ACCESS_WIFI_STATE" -> resources.getString(R.string.ACCESS_WIFI_STATE)
        "android.permission.ACCOUNT_MANAGER" -> resources.getString(R.string.ACCOUNT_MANAGER)
        "com.android.settings.permission.ALLSHARE_CAST_SERVICE" -> resources.getString(R.string.ALLSHARE_CAST_SERVICE)
        "android.permission.AUTHENTICATE_ACCOUNTS" -> resources.getString(R.string.AUTHENTICATE_ACCOUNTS)
        "android.permission.BATTERY_STATS" -> resources.getString(R.string.BATTERY_STATS)
        "com.android.vending.BILLING" -> resources.getString(R.string.BILLING)
        "android.permission.BIND_APPWIDGET" -> resources.getString(R.string.BIND_APPWIGET)
        "android.permission.BIND_DEVICE_ADMIN" -> resources.getString(R.string.BIND_DEVICE_ADMIN)
        "android.permission.BIND_INPUT_METHOD" -> resources.getString(R.string.BIND_INPUT_METHOD)
        "android.permission.BIND_WALLPAPER" -> resources.getString(R.string.BIND_WALLPAPER)
        "android.permission.BLUETOOTH" -> resources.getString(R.string.BLUETOOTH)
        "android.permission.BLUETOOTH_ADMIN" -> resources.getString(R.string.BULETOOTH_ADMIN)
        "android.permission.BRICK " -> resources.getString(R.string.BRICK)
        "android.permission.BROADCAST_PACKAGE_REMOVED" -> resources.getString(R.string.BROADCAST_PACKAGE_REMOVED)
        "android.permission.BROADCAST_SMS" -> resources.getString(R.string.BROADCAST_SMS)
        "android.permission.BROADCAST_STICKY" -> resources.getString(R.string.BROADCAST_STICKY)
        "android.permission.CALL_PHONE" -> resources.getString(R.string.CALL_PHONE)
        "android.permission.CALL_PRIVILEGED" -> resources.getString(R.string.CALL_PRIVILEGED)
        "android.permission.CAMERA" -> resources.getString(R.string.CAMERA)
        "android.permission.CHANGE_COMPONENT_ENABLED_STATE" -> resources.getString(R.string.CHANGE_COMPONENT_ENABLED_STATE)
        "android.permission.CHANGE_CONFIGURATION", "Android.permission.CHANGE_CONFIGURATION" -> resources.getString(R.string.CHANGE_CONFIGURATION)
        "android.permission.CHANGE_NETWORK_STATE" -> resources.getString(R.string.CHANGE_NETWORK_STATE)
        "android.permission.CHANGE_WIFI_MULTICAST_STATE" -> resources.getString(R.string.CHANGE_WIFIMULTICAST_STATE)
        "android.permission.CHANGE_WIFI_STATE" -> resources.getString(R.string.CHANGE_WIFI_STATE)
        "com.android.vending.CHECK_LICENSE" -> resources.getString(R.string.CHECK_LICENSE)
        "android.permission.CLEAR_APP_CACHE" -> resources.getString(R.string.CLEAR_APP_CACHE)
        "android.permission.CLEAR_APP_USER_DATA" -> resources.getString(R.string.CLEAR_APP_USER_DATA)
        "android.permission.CONTROL_LOCATION_UPDATES" -> resources.getString(R.string.CONTROL_LOCATION_UPDATES)
        "com.android.launcher.permission.CREATE_SHORTCUT" -> resources.getString(R.string.CREATE_SHORTCUT)
        "android.permission.DELETE_CACHE_FILES" -> resources.getString(R.string.DELETE_CACHE_FILES)
        "android.permission.DELETE_PACKAGES" -> resources.getString(R.string.DLEETE_PACKAGES)
        "android.permission.DEVICE_POWER" -> resources.getString(R.string.DEVICE_POWER)
        "android.permission.DIAGNOSTIC" -> resources.getString(R.string.DIAGNOSTIC)
        "android.permission.DISABLE_KEYGUARD" -> resources.getString(R.string.DISABLE_KEYGUARD)
        "android.permission.DUMP" -> resources.getString(R.string.DUMP)
        "android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" -> resources.getString(R.string.DOWNLOAD_WITHOUT_NOTIFICATION)
        "android.permission.EXPAND_STATUS_BAR" -> resources.getString(R.string.EXPAND_STATUS_BAR)
        "android.permission.FACTORY_TEST" -> resources.getString(R.string.FACTORY_TEST)
        "android.permission.FLASHLIGHT" -> resources.getString(R.string.FLSHLIGHT)
        "android.permission.FORCE_BACK" -> resources.getString(R.string.FORCE_BACK)
        "android.permission.GET_ACCOUNTS" -> resources.getString(R.string.GET_ACCOUNTS)
        "android.permission.GET_PACKAGE_SIZE" -> resources.getString(R.string.GET_PACKAGE_SIZE)
        "android.permission.GET_TASKS" -> resources.getString(R.string.GET_TASKS)
        "android.permission.GLOBAL_SEARCH" -> resources.getString(R.string.GLBOAL_SEARCH)
        "android.permission.HARDWARE_TEST " -> resources.getString(R.string.HARDWARE_TEST)
        "android.permission.INJECT_EVENTS" -> resources.getString(R.string.INJECT_EVENTS)
        "android.permission.INSTALL_PERMISSION" -> resources.getString(R.string.INSTALL_PERMISSION)
        "android.permission.INSTALL_LOCATION_PROVIDER" -> resources.getString(R.string.INSTALL_LOCATION_PROVIDER)
        "android.permission.INSTALL_PACKAGES" -> resources.getString(R.string.INSTALL_PCAKAGES)
        "com.android.launcher.permission.INSTALL_SHORTCUT" -> resources.getString(R.string.LAUNCHER_INSTALL_SHORTCUT)
        "android.permission.INTERACT_ACROSS_USERS" -> resources.getString(R.string.INTERACT_ACROSS_USERS)
        "android.permission.INTERACT_ACROSS_USERS_FULL" -> resources.getString(R.string.INTERACT_ACROSS_USERS_FULL)
        "android.permission.INTERNAL_SYSTEM_WINDOW" -> resources.getString(R.string.INTERNAL_SYSTEM_WINDOW)
        "android.permission.INTERNET" -> resources.getString(R.string.INTERNET)
        "android.permission.KILL_BACKGROUND_PROCESSES" -> resources.getString(R.string.KILL_BACKGROUND_PROCESSES)
        "android.permission.MANAGE_ACCOUNTS" -> resources.getString(R.string.MANAGE_ACCOUNTS)
        "android.permission.MANAGE_APP_TOKENS" -> resources.getString(R.string.MANAGE_APP_TOKENS)
        "android.permission.MANAGE_DOCUMENTS" -> resources.getString(R.string.MANAGE_DOCUMENTS)
        "android.permission.MANAGE_NETWORK_POLICY" -> resources.getString(R.string.MANAGE_NETWORK_POLICY)
        "android.permission.MASTER_CLEAR" -> resources.getString(R.string.MASTER_CLEAR)
        "android.permission.MODIFY_AUDIO_SETTINGS" -> resources.getString(R.string.MODIFY_AUDIO_SETTINGS)
        "android.permission.MODIFY_PHONE_STATE" -> resources.getString(R.string.MODIFY_PHONE_STATE)
        "android.permission.MOUNT_FORMAT_FILESYSTEMS" -> resources.getString(R.string.MOUNT_FORMAT_FILESYSTEMS)
        "android.permission.MOUNT_UNMOUNT_FILESYSTEMS" -> resources.getString(R.string.MOUNT_UNMOUNT_FILESYSTEMS)
        "android.permission.NFC" -> resources.getString(R.string.NFC)
        "android.permission.PERSISTENT_ACTIVITY" -> resources.getString(R.string.PERSISTENT_ACTIVITY)
        "android.permission.PROCESS_OUTGOING_CALLS" -> resources.getString(R.string.PROCESS_OUTGOING_CALLS)
        "android.permission.RAISED_THREAD_PRIORITY" -> resources.getString(R.string.RAISED_THREAD_PRIORITY)
        "android.permission.READ_CALL_LOG" -> resources.getString(R.string.READ_CALL_LOG)
        "android.permission.READ_CALENDAR" -> resources.getString(R.string.READ_CALENDAR)
        "android.permission.READ_CONTACTS" -> resources.getString(R.string.READ_CONTACTS)
        "android.permission.READ_FRAME_BUFFER" -> resources.getString(R.string.READ_FRAME_BUFFER)
        "android.permission.READ_HISTORY_BOOKMARKS" -> resources.getString(R.string.READ_HISTORY_BOOKMARKS)
        "com.android.browser.permission.READ_HISTORY_BOOKMARKS" -> resources.getString(R.string.READ_HISTORY_BOOKMARKS)
        "android.permission.READ_INPUT_STATE" -> resources.getString(R.string.READ_INPUT_STATE)
        "android.permission.READ_LOGS" -> resources.getString(R.string.READ_LOGS)
        "android.permission.READ_OWNER_DATA" -> resources.getString(R.string.READ_OWNER_DATA)
        "android.permission.READ_PHONE_STATE" -> resources.getString(R.string.READ_PHONE_STATE)
        "android.permission.READ_PROFILE" -> resources.getString(R.string.READ_PROFILE)
        "com.android.launcher.permission.READ_SETTINGS", "com.android.launcher2.permission.READ_SETTINGS", "com.android.launcher3.permission.READ_SETTINGS" -> resources.getString(R.string.LAUNCHER_READ_SETTINGS)
        "android.permission.READ_SETTINGS" -> resources.getString(R.string.READ_SETTINGS)
        "android.permission.READ_SMS" -> resources.getString(R.string.READ_SMS)
        "android.permission.READ_SYNC_SETTINGS" -> resources.getString(R.string.READ_SYNC_SETTINGS)
        "android.permission.READ_SYNC_STATS" -> resources.getString(R.string.READ_SYNC_STATS)
        "android.permission.REBOOT" -> resources.getString(R.string.REBOOT)
        "com.google.android.c2dm.permission.RECEIVE" -> resources.getString(R.string.C2DM_RECEIVE)
        "android.permission.RECEIVE_BOOT_COMPLETED" -> resources.getString(R.string.RECEIVE_BOOT_COMPLETED)
        "android.permission.RECEIVE_MMS" -> resources.getString(R.string.RECEIVE_MMS)
        "android.permission.RECEIVE_USER_PRESENT" -> resources.getString(R.string.RECEIVE_USER_PRESENT)
        "android.permission.RECEIVE_SMS" -> resources.getString(R.string.RECEIVE_SMS)
        "android.permission.RECEIVE_WAP_PUSH" -> resources.getString(R.string.RECEIVE_WAP_PUSH)
        "android.permission.RECORD_AUDIO" -> resources.getString(R.string.RECORD_AUDIO)
        "android.permission.REORDER_TASKS" -> resources.getString(R.string.REORDER_TASKS)
        "android.permission.RESTART_PACKAGES" -> resources.getString(R.string.RESTART_PACKAGES)
        "android.permission.READ_EXTERNAL_STORAGE" -> resources.getString(R.string.READ_EXTERNAL_STORAGE)
        "android.permission.READ_SECURE_SETTINGS" -> resources.getString(R.string.READ_SECURE_SETTINGS)
        "android.permission.READ_SOCIAL_STREAM" -> resources.getString(R.string.READ_SOCIAL_STREAM)
        "android.permission.RUN_INSTRUMENTATION" -> resources.getString(R.string.RUN_INSTRUMENTATION)
        "android.permission.SEND_SMS" -> resources.getString(R.string.SEND_SMS)
        "android.permission.SEND_SMS_NO_CONFIRMATION" -> resources.getString(R.string.SEND_SMS_NO_CONFIRMATION)
        "android.permission.STOP_APP_SWITCHES" -> resources.getString(R.string.STOP_APP_SWITCHES)
        "com.android.alarm.permission.SET_ALARM" -> resources.getString(R.string.SET_ALARM)
        "android.permission.SET_ACTIVITY_WATCHER" -> resources.getString(R.string.SET_ACTIVITY_WATHCER)
        "android.permission.SET_ALWAYS_FINISH" -> resources.getString(R.string.SET_ALWAYS_FINISH)
        "android.permission.SET_ANIMATION_SCALE" -> resources.getString(R.string.SET_ANIMATION_SCALE)
        "android.permission.SET_DEBUG_APP" -> resources.getString(R.string.SET_DEBUG_APP)
        "android.permission.SET_ORIENTATION" -> resources.getString(R.string.SET_ORIENTATION)
        "android.permission.SET_PROCESS_LIMIT" -> resources.getString(R.string.SET_PROCESS_LIMIT)
        "android.permission.SET_TIME" -> resources.getString(R.string.SET_TIME)
        "android.permission.SET_TIME_ZONE" -> resources.getString(R.string.SET_TIME_ZONE)
        "android.permission.SET_WALLPAPER" -> resources.getString(R.string.SET_WALLPAPER)
        "android.permission.SET_WALLPAPER_HINTS" -> resources.getString(R.string.SET_WALLPAPER_HINTS)
        "android.permission.SET_PREFERRED_APPLICATIONS" -> resources.getString(R.string.SET_PREFERRED_APPLICATIONS)
        "android.permission.SIGNAL_PERSISTENT_PROCESSES" -> resources.getString(R.string.SIGNAL_PERSISTENT_PROCESSES)
        "android.permission.START_BACKGROUND_SERVICE" -> resources.getString(R.string.START_BACKGROUND_SERVICE)
        "android.permission.STATUS_BAR" -> resources.getString(R.string.STATUS_BAR)
        "android.permission.SUBSCRIBED_FEEDS_READ" -> resources.getString(R.string.SUBSCRIBED_FEEDS_READ)
        "android.permission.SUBSCRIBED_FEEDS_WRITE" -> resources.getString(R.string.SUBSRIBED_FEEDS_WRITE)
        "android.permission.SYSTEM_ALERT_WINDOW" -> resources.getString(R.string.SYSYTEM_ALERT_WINDOW)
        "android.permission.SYSTEM_OVERLAY_WINDOW" -> resources.getString(R.string.SYSTEM_OVERLAY_WINDOW)
        "android.permission.UPDATE_DEVICE_STATS" -> resources.getString(R.string.UPDATE_DEVICE_STATS)
        "android.permission.USE_CREDENTIALS" -> resources.getString(R.string.USE_CREDENTIALS)
        "com.android.launcher.permission.UNINSTALL_SHORTCUT" -> resources.getString(R.string.LAUNCHER_UNINSTALL_SHORTCUT)
        "android.permission.VIBRATE" -> resources.getString(R.string.VIBRATE)
        "com.android.launcher.permission.WRITE_SETTINGS" -> resources.getString(R.string.LAUNCHER_WRITE_SETTINGS)
        "android.permission.WAKE_LOCK" -> resources.getString(R.string.WAKE_LOCK)
        "android.permission.WAP_PUSH" -> resources.getString(R.string.WAP_PUSH)
        "android.permission.WRITE_APN_SETTINGS" -> resources.getString(R.string.WRITE_APN_SETTINGS)
        "android.permission.WRITE_CALENDAR" -> resources.getString(R.string.WRITE_CALENDAR)
        "android.permission.WRITE_CALL_LOG" -> resources.getString(R.string.WRITE_CALL_LOG)
        "android.permission.WRITE_CONTACTS" -> resources.getString(R.string.WRITE_CONTACTS)
        "android.permission.WRITE_EXTERNAL_STORAGE" -> resources.getString(R.string.WRITE_EXTERNAL_STORAGE)
        "android.permission.WRITE_GSERVICES" -> resources.getString(R.string.WRITE_GSERVICES)
        "android.permission.WRITE_HISTORY_BOOKMARKS", "com.android.browser.permission.WRITE_HISTORY_BOOKMARKS" -> resources.getString(R.string.WRITE_HISTORY_BOOKMARKS)
        "android.permission.WRITE_INTERNAL_STORAGE" -> resources.getString(R.string.WRITE_INTERNAL_STORAGE)
        "android.permission.WRITE_OWNER_DATA" -> resources.getString(R.string.WRITE_OWNER_DATA)
        "android.permission.WRITE_PROFILE" -> resources.getString(R.string.WRITE_PROFILE)
        "android.permission.WRITE_SECURE_SETTINGS" -> resources.getString(R.string.WRITE_SECURE_SETTINGS)
        "android.permission.WRITE_SETTINGS" -> resources.getString(R.string.WRITE_SETTINGS)
        "android.permission.WRITE_SMS" -> resources.getString(R.string.WRITE_SMS)
        "android.permission.WRITE_SYNC_SETTINGS" -> resources.getString(R.string.WRITE_SYNC_SETTINGS)
        "android.permission.WRITE_MEDIA_STORAGE" -> resources.getString(R.string.WRITE_MEDIA_STORAGE)
        "android.permission.SEND_DOWNLOAD_COMPLETED_INTENTS" -> resources.getString(R.string.SEND_DOWNLOAD_COMPLETED_INTENTS)
        "android.permission.RECORD_VIDEO" -> resources.getString(R.string.RECORD_VIDEO)
        "android.permission.UPDATE_APP_OPS_STATS" -> resources.getString(R.string.UPDATE_APP_OPS_STATS)
        "android.permission.ACCESS_DEV_STORAGE" -> resources.getString(R.string.ACCESS_DEV_STORAGE)
        "android.permission.MANAGE_DEVICE_ADMINS" -> resources.getString(R.string.MANAGE_DEVICE_ADMINS)
        "android.permission.ACCESS_NOTIFICATIONS" -> resources.getString(R.string.ACCESS_NOTIFICATIONS)
        "android.permission.ACCESS_WIMAX_STATE" -> resources.getString(R.string.ACCESS_WIMAX_STATE)
        "android.permission.CHANGE_WIMAX_STATE" -> resources.getString(R.string.CHANGE_WIMAX_STATE)
        "android.permission.FORCE_STOP_PACKAGES" -> resources.getString(R.string.FORCE_STOP_PACKAGES)
        "android.permission.PACKAGE_USAGE_STATS" -> resources.getString(R.string.PACKAGE_USAGE_STATS)
        "android.permission.MOVE_PACKAGE" -> resources.getString(R.string.MOVE_PACKAGE)
        "android.permission.BACKUP" -> resources.getString(R.string.BACKUP)
        "android.permission.MANAGE_USB" -> resources.getString(R.string.MANAGE_USB)
        "android.permission.SET_POINTER_SPEED" -> resources.getString(R.string.SET_POINTER_SPEED)
        "android.permission.SET_KEYBOARD_LAYOUT" -> resources.getString(R.string.SET_KEYBOARD_LAYOUT)
        "android.permission.MANAGE_USERS" -> resources.getString(R.string.MANAGE_USERS)
        "android.permission.CONFIGURE_WIFI_DISPLAY" -> resources.getString(R.string.CONFIGURE_WIFI_DISPLAY)
        else -> permission
    }
}
